### ISSUE TITLE
doesn't work on NVME drives

### ISSUE THREAD

**Issue by RobertSpir** [Elinvention/efibootmgr-gui#10]
when running on NVME drive where the partitions are named `/dev/nvme0n1p1`
it fails with
```python efibootmgr_gui.py 
findmnt --noheadings --output SOURCE --target /boot/efi
/dev/nvme0n1p1
Could not parse device path: Invalid argument
Command '['efibootmgr', '-v']' returned non-zero exit status 18.
```
Here the argument for efibootmgr should be `--disk /dev/nvme0n1p1`

**Comment by Elinvention** [comment]
Have you tried calling the program with that argument?

I don't think my program makes assumptions about the device name. What happens if you run `efibootmgr -v` in a shell? The log says that efibootmgr returned status -18, so I'd first investigate that.

**Comment by kekkokk** [comment]
I had the same problem. when efibootmgr-gui tries to invoke the command a "p" is appended to /dev/nvme0n1p1 and the command fail.

trying without "p" works: `sudo efibootmgr --disk /dev/nvme0n1 --part 2 --create --label 'Refind' --loader 'EFI\refind\refind_x64.efi'`

maybe related: [https://github.com/JohnstonJ/ubuntu-secure-boot/issues/2](url)

**Comment by Elinvention** [comment]
Oh ok, I got it. I'll fix that soon.

**Comment by Elinvention** [comment]
Should work now™
