### ISSUE TITLE
crash/segfault with python 3.5 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ethchest** [Elinvention/efibootmgr-gui#5]
Ok, something a bit weird. When I run `python3 efibootmgr-gui.py` it crashes with a segfault in gtk_list_store_reorder(). But when I then tried just `efibootmgr-gui.py` it started once. Now after trying it again that crashes too. I have the whole crash report with trace etc available if you want to take a look at it.

**Comment by Elinvention** [comment]
Perhaps you are running two different python interpreters. If you run `./efibootmgr-gui.py` you are actually running `/usr/bin/env python3 efibootmgr-gui.py` which will look in all your directories in $PATH for a python executable, but if you run `python3 efibootmgr-gui.py` it depends on the behavior of your shell. You may have a python alias or some other odd config.
You would check the $PATH variable and run `which python3` or `where python3` if you use zsh.

**Comment by ethchest** [comment]
Mmh, thanks for your reply. Yeah I know that env and shell work slightly differently.

Both by running env/which but also by putting `print(sys.version)` at the start of efibootmgr-gui.py, both versions seem to be the same, as the version and the date and gcc version they were compiled with are exactly the same.

**Comment by Elinvention** [comment]
Re-reading your first comment, now it crashes always with both commands, right? 

Let's ignore the fact that it started once, as that will probably remain a mistery. Then I need the trace and the output of `efibootmgr` (probably there are possible outputs which I didn't consider). Thanks.

**Comment by ethchest** [comment]
efibootmgr output:
```
BootCurrent: 0019
Timeout: 0 seconds
BootOrder: 001A,0019,001B,0022,0080,0000,0001,0002,0003,0007,0008,0009,000A,0011,000C,000D,000B,000F,0010,0012,000E
Boot0000  Setup
Boot0001  Boot Menu
Boot0002  Diagnostic Splash Screen
Boot0003  Lenovo Diagnostics
Boot0004  Startup Interrupt Menu
Boot0005  ME Configuration Menu
Boot0006  Rescue and Recovery
Boot0007* USB CD
Boot0008  USB FDD
Boot0009  ATAPI CD0
Boot000A* ATA HDD0
Boot000B* ATA HDD1
Boot000C  ATA HDD2
Boot000D* USB HDD
Boot000E  PCI LAN
Boot000F  ATAPI CD1
Boot0010  Other CD
Boot0011* ATA HDD3
Boot0012  Other HDD
Boot0013* IDER BOOT CDROM
Boot0014* IDER BOOT Floppy
Boot0015* ATA HDD
Boot0016* ATAPI CD:
Boot0017* PCI LAN
Boot0019* ubuntu
Boot001A* Windows Boot Manager
Boot001B* rEFInd Boot Manager
Boot0022* Clover
Boot0080* Mac OS X
```

(most of these are fixed BIOS entries and cannot be removed, only disabled)

Crash report here: https://pastebin.com/A0kvKz6X (this is what ubuntu crash reporting saved, minus the core dump and I thought there might have been more but that didn't get saved or I am mixing things up)

**Comment by kaendfinger** [comment]
This seems to be related to ListStore.reorder, which is possibly not available anymore?

**Comment by Elinvention** [comment]
Is this still happening?

**Comment by kaendfinger** [comment]
This still happens for me with Python 3.7 on Arch Linux
