### ISSUE TITLE
Locks up after the 5th pkexec

### ISSUE THREAD

**Issue by HughPH** [Elinvention/efibootmgr-gui#6]
I say "locks up" - it holds my SSD in a busy state. Processes run for a bit, but then everything grinds to a halt. I had tty2 open to run iotop to see if I could figure out what was going on. I couldn't, but it told me this:

Killed process _xxxxx_ (python3) total-vm:62715315kB, anon-rss:31522500kB, file-rss:2304kB, shmem-rs:16kB

Run 1:
pkexec efibootmgr --disk /dev/sda --part 1 --bootnum 0008 --inactive
pkexec efibootmgr --disk /dev/sda --part 1 --bootnum 0009 --inactive
pkexec efibootmgr --disk /dev/sda --part 1 --bootnum 0002 --inactive
pkexec efibootmgr --disk /dev/sda --part 1 --bootnum 0001 --inactive
pkexec efibootmgr --disk /dev/sda --part 1 --bootnum 0000 --inactive
Killed

Run 2:
pkexec efibootmgr --disk /dev/sda --part 1 --delete-bootnum --bootnum 0000
pkexec efibootmgr --disk /dev/sda --part 1 --delete-bootnum --bootnum 0008
pkexec efibootmgr --disk /dev/sda --part 1 --delete-bootnum --bootnum 0001
pkexec efibootmgr --disk /dev/sda --part 1 --delete-bootnum --bootnum 0002
pkexec efibootmgr --disk /dev/sda --part 1 --bootnext 0009
Killed

**Comment by HughPH** [comment]
I can confirm it's 5 times, because if there are fewer than 5 actions, it doesn't lock up.

**Comment by Elinvention** [comment]
Can you check if the latest commit fixed this issue? Thanks.

**Comment by HughPH** [comment]
Yes, this fixed the issue.
