### ISSUE TITLE
Double quota

### ISSUE THREAD

**Issue by riccardoprandini01** [Elinvention/efibootmgr-gui#9]
Hi,
i have used your program under Fedora 31 i lost a UEFI boot entry the program is very useful, the part that show the command is very important, it solves my problem.

I have only one issue
the loader part need double quota

sudo efibootmgr --disk /dev/sda --part 1 --create --label fedora --loader "\EFI\fedora\grubx64.efi"

**Comment by Elinvention** [comment]
I added single quotes instead of double to avoid variable substitution by sh.
